import { Button } from "antd";
import { TYPE_ACTION_AUTH } from "common/typeActionRedux";
import MainLayout from "layouts/mainLayout";
import Head from "next/head";
import Image from "next/image";
import { useDispatch, useSelector } from "react-redux";
import { wrapper } from "redux/store";
import styles from "../styles/Home.module.css";
import { AppPropsWithLayout } from "./_app";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
}

Home.getLayout = function getLayout(page: AppPropsWithLayout) {
  return <MainLayout>{page}</MainLayout>;
};
export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    ({ req, res, ...etc }) => {
      store.dispatch({ type: TYPE_ACTION_AUTH.SET_AUTH_STATE });
      store.dispatch({ type: TYPE_ACTION_AUTH.SET_TOTAL, payload: 10 });
    }
);
